2025-01-14 14:52:04,341 = | WARNING = | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\andre\pythonUniversityProjects\Homeworks\МОДУЛЬ 11 - Стандартные и сторонние библиотеки Python\UnitTests\Logging\tests_12_4.py", line 23, in test_run
    r = Runner(1000)
        ^^^^^^^^^^^^
  File "C:\Users\andre\pythonUniversityProjects\Homeworks\МОДУЛЬ 11 - Стандартные и сторонние библиотеки Python\UnitTests\Logging\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-01-14 14:52:04,343 = | WARNING = | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\andre\pythonUniversityProjects\Homeworks\МОДУЛЬ 11 - Стандартные и сторонние библиотеки Python\UnitTests\Logging\tests_12_4.py", line 12, in test_walk
    r = Runner('daadd', -5)
        ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\pythonUniversityProjects\Homeworks\МОДУЛЬ 11 - Стандартные и сторонние библиотеки Python\UnitTests\Logging\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
